//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team1_Web_ADProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllStaffRequisition
    {
        public string Description { get; set; }
        public string UoM { get; set; }
        public int QuantityBackOrdered { get; set; }
        public string DepartmentCode { get; set; }
        public string EmployeeName { get; set; }
        public string FormID { get; set; }
        public string EmployeeID { get; set; }
        public string ApprovalStatus { get; set; }
        public string Status { get; set; }
    }
}
