
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SA46Team1_Web_ADProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ApprovalDelegation
{

    public int Id { get; set; }

    public System.DateTime DateAssigned { get; set; }

    public byte Active { get; set; }

    public string EmployeeID { get; set; }

    public System.DateTime FromDate { get; set; }

    public System.DateTime ToDate { get; set; }

}

}
