
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SA46Team1_Web_ADProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RequisitionList
{

    public System.DateTime DateRequested { get; set; }

    public string FormID { get; set; }

    public string DepartmentName { get; set; }

    public string Status { get; set; }

}

}
