//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team1_Web_ADProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionListDetail
    {
        public string FormID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentCode { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeID { get; set; }
        public string Manager { get; set; }
        public System.DateTime DateProcessed { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public int QuantityOrdered { get; set; }
        public int QuantityDelivered { get; set; }
    }
}
