//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team1_Web_ADProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRetrievalHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockRetrievalHeader()
        {
            this.DisbursementHeaders = new HashSet<DisbursementHeader>();
            this.StockRetrievalDetails = new HashSet<StockRetrievalDetail>();
            this.StockRetrievalReqForms = new HashSet<StockRetrievalReqForm>();
        }
    
        public string ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> Disbursed { get; set; }
        public Nullable<byte> AllItemsRetrieved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementHeader> DisbursementHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRetrievalDetail> StockRetrievalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRetrievalReqForm> StockRetrievalReqForms { get; set; }
    }
}
