
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SA46Team1_Web_ADProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StockCount
{

    public int Year { get; set; }

    public int Month { get; set; }

    public string ItemCode { get; set; }

    public int ItemQuantity { get; set; }

    public float AverageUnitCost { get; set; }

}

}
