//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team1_Web_ADProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeDetail
    {
        public int StockTakeID { get; set; }
        public string ItemCode { get; set; }
        public int QuantityOnHand { get; set; }
        public int QuantityCounted { get; set; }
        public int QuantityAdjusted { get; set; }
        public string Remarks { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual StockTakeHeader StockTakeHeader { get; set; }
    }
}
