//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SA46Team1_Web_ADProj.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier
{

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Items = new HashSet<Item>();
            this.Items1 = new HashSet<Item>();
            this.Items2 = new HashSet<Item>();
            this.POHeaders = new HashSet<POHeader>();
            this.SupplierPriceLists = new HashSet<SupplierPriceList>();
        }

        public string SupplierCode { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public int PhoneNo { get; set; }
        public Nullable<int> FaxNo { get; set; }
        public string Address { get; set; }
        public string GSTRegistrationNo { get; set; }
        public byte Active { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POHeader> POHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPriceList> SupplierPriceLists { get; set; }

    }

}
